#!/usr/bin/env python3
"""Analyze CSVs generated by profile_pyspacemouse.py.

Expected usage from the repository root:
    pixi run python aic_utils/tools/analyze_pyspacemouse.py
"""

from __future__ import annotations

import argparse
import glob
import os


AXES = ("X", "Y", "Z", "Pitch", "Roll", "Yaw")


def require_pandas():
    try:
        import pandas as pd
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency: pandas. It is provided by the AIC Pixi "
            "environment; run with "
            "`pixi run python aic_utils/tools/analyze_pyspacemouse.py ...` "
            "from the repository root."
        ) from exc

    return pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze SpaceMouse separation and latency profile CSVs."
    )
    parser.add_argument(
        "--input-dir",
        default="./profiles",
        help="Directory containing generated SpaceMouse profile CSV files.",
    )
    parser.add_argument(
        "--mode",
        choices=("separation", "latency", "both"),
        default="latency",
        help="Analysis mode to run.",
    )
    parser.add_argument(
        "--bleed-threshold",
        type=float,
        default=0.05,
        help="Mean absolute off-axis value above which cross-talk is reported.",
    )
    return parser.parse_args()


def analyze_profiles(input_dir: str, bleed_threshold: float) -> None:
    pd = require_pandas()

    csv_files = sorted(glob.glob(os.path.join(input_dir, "profile_*.csv")))

    if not csv_files:
        print(f"\n[!] No separation profile CSV files found in: {input_dir}")
        return

    print("\n==================================================")
    print("      SPACEMOUSE CROSS-TALK & BLEED ANALYSIS      ")
    print("==================================================")
    print("Values represent mean absolute intensity from 0.0 to 1.0.")

    for file_path in csv_files:
        filename = os.path.basename(file_path)
        intended_axis = filename.removeprefix("profile_").removesuffix(".csv").upper()

        try:
            df = pd.read_csv(file_path)
        except Exception as exc:
            print(f"Error reading {filename}: {exc}")
            continue

        if df.empty:
            print(f"WARNING: {filename} is empty.")
            continue

        print(f"\nWhen you intended to move only axis: [{intended_axis}]")
        print("-" * 50)

        bleed_found = False
        for column in AXES:
            avg_signal = df[column].abs().mean()

            if column.upper() == intended_axis:
                print(f"  Target channel [{column}]: Avg magnitude = {avg_signal:.3f}")
            elif avg_signal > bleed_threshold:
                print(f"    BLEED on [{column}]: Avg magnitude = {avg_signal:.3f}")
                bleed_found = True
            else:
                print(f"    Clear [{column}]: Avg magnitude = {avg_signal:.3f}")

        if not bleed_found:
            print("  Clean separation; no cross-talk above threshold.")


def analyze_latency(input_dir: str) -> None:
    pd = require_pandas()

    csv_files = sorted(glob.glob(os.path.join(input_dir, "latency_profile*.csv")))

    if not csv_files:
        print(f"\n[!] No latency profile CSV files found in: {input_dir}")
        return

    print("\n==================================================")
    print("          SPACEMOUSE LATENCY ANALYSIS             ")
    print("==================================================")

    frames = []
    for file_path in csv_files:
        filename = os.path.basename(file_path)
        try:
            df = pd.read_csv(file_path)
        except Exception as exc:
            print(f"Error reading {filename}: {exc}")
            continue

        if df.empty:
            print(f"WARNING: {filename} is empty.")
            continue

        df["Profile_File"] = filename
        frames.append(df)

    if not frames:
        print("[!] No non-empty latency profile data found.")
        return

    combined = pd.concat(frames, ignore_index=True)
    print(f"Files analyzed: {len(frames)}")
    print(f"Samples analyzed: {len(combined)}")

    avg_loop = combined["Loop_Time"].mean() * 1000.0
    max_loop = combined["Loop_Time"].max() * 1000.0
    print("\nLocal processing loop performance:")
    print(f"   - Average cycle time: {avg_loop:.2f} ms")
    print(f"   - Peak cycle time: {max_loop:.2f} ms")

    numeric_latency = pd.to_numeric(combined["Read_Latency"], errors="coerce")
    if numeric_latency.isnull().all():
        print(
            "\nHardware driver timestamps were not exposed by the current OS/hidraw "
            "backend."
        )
        print(
            "The local processing loop ingested events at an average interval of "
            f"{avg_loop:.2f} ms."
        )
        return

    avg_latency = numeric_latency.mean() * 1000.0
    max_latency = numeric_latency.max() * 1000.0
    print("\nDriver/ingestion lag metrics:")
    print(f"   - Average hardware ingestion delay: {avg_latency:.2f} ms")
    print(f"   - Maximum hardware ingestion delay: {max_latency:.2f} ms")

    print("\nPer-file loop averages:")
    for filename, group in combined.groupby("Profile_File"):
        avg_file_loop = group["Loop_Time"].mean() * 1000.0
        print(f"   - {filename}: {avg_file_loop:.2f} ms")


def main() -> None:
    args = parse_args()

    if args.mode in ("separation", "both"):
        analyze_profiles(args.input_dir, args.bleed_threshold)

    if args.mode in ("latency", "both"):
        analyze_latency(args.input_dir)


if __name__ == "__main__":
    main()
