"""OpenAI VLM planner for slow official teacher oracle runs."""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path
import re
import shlex
from typing import Any

import numpy as np

from aic_teacher_official.context import OfficialTeacherContext


def load_openai_api_key() -> str | None:
    if os.environ.get("OPENAI_API_KEY"):
        return os.environ["OPENAI_API_KEY"]
    zshrc = Path.home() / ".zshrc"
    if not zshrc.exists():
        return None
    pattern = re.compile(r"^\s*(?:export\s+)?OPENAI_API_KEY=(.*)\s*$")
    for line in zshrc.read_text(encoding="utf-8", errors="ignore").splitlines():
        match = pattern.match(line)
        if not match:
            continue
        value = match.group(1).strip()
        if value:
            return shlex.split(value)[0]
    return None


def _image_items(image_paths: list[Path]) -> list[dict[str, Any]]:
    items = []
    for path in image_paths:
        suffix = path.suffix.lower().lstrip(".")
        mime = "jpeg" if suffix in {"jpg", "jpeg"} else "png"
        data = base64.b64encode(path.read_bytes()).decode("ascii")
        items.append(
            {
                "type": "input_image",
                "image_url": f"data:image/{mime};base64,{data}",
                "detail": "low",
            }
        )
    return items


def _extract_output_text(response: Any) -> str:
    text = getattr(response, "output_text", None)
    if text:
        return str(text)
    output = getattr(response, "output", None) or []
    chunks: list[str] = []
    for item in output:
        for content in getattr(item, "content", []) or []:
            if getattr(content, "type", "") == "output_text":
                chunks.append(str(getattr(content, "text", "")))
    return "\n".join(chunks)


def call_gpt5_mini_delta_planner(
    context: OfficialTeacherContext,
    *,
    image_paths: list[Path] | None = None,
    planner_feedback: dict[str, Any] | None = None,
    max_calls: int = 20,
    model: str = "gpt-5-mini",
    request_timeout_sec: float = 120.0,
) -> dict[str, Any]:
    """Ask GPT-5 mini for approach/alignment Cartesian delta waypoints.

    This function is intentionally slow-run only. Replay imports do not depend
    on this module.
    """
    if max_calls < 1 or max_calls > 20:
        raise ValueError("max_calls must be in [1, 20]")
    api_key = load_openai_api_key()
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not set and could not be read from ~/.zshrc. "
            "Export it before using --use-vlm."
        )
    try:
        from openai import OpenAI
    except Exception as ex:
        raise RuntimeError("The openai Python package is required for --use-vlm.") from ex

    image_paths = image_paths or []
    client = OpenAI(api_key=api_key)
    prompt = {
        "task": "Plan approach/alignment only for robot TCP trajectory.",
        "hard_constraints": [
            "Return Cartesian delta waypoints in base_link frame, not joints.",
            "Do not plan final insertion; final insertion is generated by CheatCode geometry.",
            "Keep waypoint count small: 2 to 4 approach/alignment deltas.",
            "Each delta is relative to the previous TCP waypoint in meters.",
            "Prefer conservative z clearance before moving near the port.",
        ],
        "context": context.to_dict(),
        "previous_loop_feedback": planner_feedback,
        "response_schema": {
            "waypoints": [
                {
                    "phase": "approach|obstacle_avoidance|alignment|pre_insertion",
                    "delta_xyz": [0.0, 0.0, 0.0],
                    "duration": 1.0,
                    "rationale": "short explanation",
                }
            ],
            "diagnostics": {"notes": "string"},
        },
    }
    response = client.responses.create(
        model=model,
        timeout=request_timeout_sec,
        instructions=(
            "You are a robotics trajectory planner. Output JSON only. "
            "Use Cartesian delta waypoints in meters in base_link."
        ),
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": json.dumps(prompt, indent=2)},
                    *_image_items(image_paths[:8]),
                ],
            }
        ],
    )
    output_text = _extract_output_text(response)
    try:
        parsed = json.loads(output_text)
    except json.JSONDecodeError as ex:
        raise RuntimeError(f"VLM planner returned non-JSON output: {output_text[:500]}") from ex
    parsed.setdefault("diagnostics", {})
    parsed["diagnostics"].update(
        {
            "model": model,
            "api_calls_used": 1,
            "max_calls_budget": max_calls,
            "image_count": len(image_paths[:8]),
            "prompt_format": "cartesian_delta_waypoints_base_link",
            "planner_feedback_used": planner_feedback is not None,
        }
    )
    return parsed


def sanitize_delta_plan(plan: dict[str, Any]) -> list[dict[str, Any]]:
    waypoints = plan.get("waypoints")
    if not isinstance(waypoints, list):
        raise ValueError("VLM plan must contain a list field: waypoints")
    sanitized = []
    for index, waypoint in enumerate(waypoints[:4]):
        delta = np.asarray(waypoint.get("delta_xyz", []), dtype=np.float64)
        if delta.shape != (3,):
            raise ValueError(f"VLM waypoint {index} must contain delta_xyz length 3")
        delta = np.clip(delta, [-0.25, -0.25, -0.15], [0.25, 0.25, 0.25])
        duration = float(waypoint.get("duration", 1.0))
        sanitized.append(
            {
                "phase": str(waypoint.get("phase", "approach")),
                "delta_xyz": delta.tolist(),
                "duration": float(np.clip(duration, 0.5, 4.0)),
                "rationale": str(waypoint.get("rationale", "")),
            }
        )
    if not sanitized:
        raise ValueError("VLM plan produced no usable waypoints")
    return sanitized
